default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "password") %>
  host: <%= ENV.fetch("MYSQL_HOST", "db") %>

development:
  <<: *default
  database: records_management_gamefiction_development

test:
  <<: *default
  database: records_management_gamefiction_test

production:
  <<: *default
  database: records_management_gamefiction_production
  username: records_management_gamefiction
  password: <%= ENV['RECORDS_MANAGEMENT_GAMEFICTION_DATABASE_PASSWORD'] %>
